language: generic

services:
    - docker

before_install:
    - docker build -t 1101174182/testing_react -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true 1101174182/testing_react npm test

after_success:
    - docker build -t multi-client ./client
    - docker build -t multi-nginx ./nginx
    - docker build -t multi-api ./api
    - docker build -t multi-worker ./worker
    - docker login -u "$docker_id" -p "$docker_password" docker.io
    - docker tag multi-client 1101174182/multi-client
    - docker push 1101174182/multi-client
    - docker tag multi-nginx 1101174182/multi-nginx
    - docker push 1101174182/multi-nginx
    - docker tag multi-api 1101174182/multi-api
    - docker push 1101174182/multi-api
    - docker tag multi-worker 1101174182/multi-worker
    - docker push 1101174182/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env-1
    bucker_name: elasticbeanstalk-us-east-2-586928785119
    docker_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY