language: generic

services:
    - docker

before_install:
    - docker build -t marasyad/testing_react -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true marasyad/testing_react npm test

after_success:
    - docker build -t marasyad/multi-client ./client
    - docker build -t marasyad/multi-nginx ./nginx
    - docker build -t marasyad/multi-api ./api
    - docker build -t marasyad/multi-worker ./worker
    - docker login -u "$docker_id" -p "$docker_password" docker.io
    - docker push marasyad/multi-client
    - docker push marasyad/multi-nginx
    - docker push marasyad/multi-api
    - docker push marasyad/multi-worker